# -*- coding: utf-8 -*-
"""HW1_Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sRY10e1yamCRkFPS2kPJCuocUm1XQpf7

**Import packages**
"""

# Numerical Operations
import math
import numpy as np

# Progress bar
from tqdm import tqdm

# Pytorch
import torch
import torch.optim as optim

# Plotting learning curve
from matplotlib import pyplot as plt

"""**Dataset**"""

#Linear Couette flow
H=1
z=np.arange(0,1.1,0.1)
U=10
u=z*U/H+np.random.randn(len(z))
plt.scatter(u,z)
plt.xlabel("u velocity (m/s)")
plt.ylabel("z height (m)")

#Put datas into torch tensor
z=torch.tensor(z)
u=torch.tensor(u)
'''advanced level'''
data=list(zip(z, u))

"""**Model**"""

#Linear model
def model(x,w,b):
    return w*x+b

"""**Loss function**"""

#Mean Square Error Loss
def loss_fn(x_p,y):
    loss_fn=(x_p-y)**2
    return loss_fn.mean()

"""**Derivative of loss function**"""

#Taking derivative by calculus
def grad_fn(x_p,x,y):
    dloss_dw=2*(x_p-y)*x
    dloss_db=2*(x_p-y)*1.0
    return torch.stack([dloss_dw.mean(), dloss_db.mean()])

"""**Optimizer**"""

#Gradient descent
def gradient_descent(params,lr,grad):
    params=params-lr*grad
    return params

"""**Training loop**"""

#Parameters update
def training(train_data,val_data,params,n_epoch,lr,patience):
    w, b=params

    '''intermediate level'''
    optimizer=optim.SGD([w, b], lr=lr, weight_decay=0.001)

    '''advanced level'''
    best_val_loss=float('inf')
    epochs_no_improve=0

    for epoch in range(1, n_epoch+1):
        # training set
        train_z,train_u=zip(*train_data)
        train_u=torch.tensor(train_u)
        train_z=torch.tensor(train_z)

        x_p_train=model(train_z,w,b)
        train_loss=loss_fn(x_p_train,train_u)

        # validation set
        val_z,val_u=zip(*val_data)
        val_u=torch.tensor(val_u)
        val_z=torch.tensor(val_z)

        x_p_val=model(val_z,w,b)
        val_loss=loss_fn(x_p_val,val_u)

        '''intermediate level'''
        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        '''advanced level'''
        if epoch%10==0:
          print(f'Epoch:{epoch}, Training Loss:{train_loss.item():.4f}, Validation Loss:{val_loss.item():.4f}')

        if val_loss < best_val_loss:
          best_val_loss=val_loss
          epochs_no_improve=0
        else:
          epochs_no_improve=epochs_no_improve+1

        if epochs_no_improve >= patience:
          print(f'--------------------------------------------------------\nEarly stopping at epoch {epoch}')
          break

    return params

"""**Dataset splitting**"""

'''advanced level'''
data_size=len(data)
train_size=int(0.8*data_size)
val_size=data_size-train_size

train_data, val_data=torch.utils.data.random_split(data, [train_size, val_size])

"""**Configuration**"""

'''basic level'''
params=[torch.tensor(15.0, requires_grad=True), torch.tensor(8.0, requires_grad=True)]
config={
    "number epoch": 3000, # number of epoch, suggest from 100 to 50000
    "learning rate": 0.001, # learning rate, suggest from 1e-2 to 1e-5
    "patience": 10, # Early Stopping's parameter
    }

"""**Training !**"""

params=training(train_data,val_data,params,config["number epoch"],config["learning rate"],config["patience"])

"""**Plot the result**"""

w,b=params
z_p=model(z,w,b)
fig=plt.figure(dpi=100)
plt.plot(z_p.detach().numpy(),z.detach().numpy())
plt.plot(u.numpy(),z.numpy(), 'o')
plt.xlabel("u velocity (m/s)")
plt.ylabel("z height (m)")